### ISSUE TITLE
Natchez Xray Fails to Connect Requests from Service to Service

### ISSUE THREAD

**Issue by albin-kv** [typelevel/natchez#1002]
**Problem:**
Natchez Xray isn't linking serivce-to-service HTTP requests smoothly with AWS Xray tracing, even though the AWS Xray tracer header is present.

![wrong xray](https://github.com/typelevel/natchez/assets/152964006/9f29aabf-1fe5-42ad-8c7a-4f46ce2566b8)
Although the trace id is the same, requests to another service shows up as another flow/tree(webdealer service hits /search endpoint in search service)

**Impact:**
This messes up the AWS Xray UI, displaying disjointed request trees instead of a single flow. It's a headache for developers trying to troubleshoot and analyze request journeys.

Solution:
We've identified and PR'ed a fix - #1001 . Enhancing Natchez Xray to recognize and use the AWS Xray tracer header properly will ensure seamless request tracing.

![right xray](https://github.com/typelevel/natchez/assets/152964006/9021839c-9503-4550-849b-2706af3fef28)
Search service is now part of the webdealer flow after webdealer service hits /search endpoint.

Action:
We kindly request the maintainers of Natchez to review our PR and consider integrating the proposed solution into the main codebase.

Thanks for your attention to this issue.

**Comment by mpilquist** [comment]
Thanks for the great writeup and PR!

Closed by #1001.
