### ISSUE TITLE
`DDSpan` propagate error to parent span

### ISSUE THREAD

**Issue by wahtique** [typelevel/natchez#734]
Hi !

I have a project implementing retries on network calls using `cats-retry`. This seemed to result in an apparently weird behaviour where when at least one retry was done then the whole resquest was marked as error even though our service responds with a 200, ie. `"error" -> true` is added to the root span the trace. 

![image](https://user-images.githubusercontent.com/55251330/220573446-02672fd8-36f7-4bc1-91e8-29ef7ceb01c6.png)

This seems to be linked to this bit which propagate a span error status to their parent 

https://github.com/tpolecat/natchez/blob/08ec0cc98162aa9e21db7a00538251b616edffe1/modules/datadog/src/main/scala/DDSpan.scala#L104-L113

which is a behaviour we see only in the Datadog span. Neither Jaeger nor OpenTelemetry spans do this. Is there any reason for this ?

**Comment by mpilquist** [comment]
I don't know of any reason we'd need to propagate there.

**Comment by wahtique** [comment]
Would you say it's safe to remove this then ?
