### ISSUE TITLE
Is there a way to filter spans with Natchez?

### ISSUE THREAD

**Issue by metasim** [typelevel/natchez#890]
We are using Natchez with Skunk, and our tracing payloads heavily populated with low-level database operations from Skunk that we generally don't want to include them in our traces. Is there a way (like with logging frameworks) whereby you can filter out spans that come from a dependent packages? Or is it "all or nothing"?

**Comment by mpilquist** [comment]
I ran in to a similar issue when using Skunk, which motivated this feature: https://github.com/typelevel/natchez/pull/665

With that said, Skunk 1.0 will move to [otel4s](https://github.com/typelevel/otel4s) which doesn't have an equivalent feature IIRC.

**Comment by metasim** [comment]
Thanks for the help @mpilquist!! 😄
